# This workflow will automatically generate and compile a LaTeX specification document
# from the LabOP ontology and upload it as an artifact

name: Python package

on:
  push:
  pull_request:
  # Schedule a nightly build. Times are UTC
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
  schedule:
    # 5:15 am UTC (https://en.wikipedia.org/wiki/5:15)
    - cron: '15 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sbol_factory
          # Install pdflatex
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          # Instal labOp
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd ..
          git clone https://github.com/Bioprotocols/labop.git
      - name: Generate spec document
        run: |
          cd ../labop/doc
          python generate_specification_content.py
          cd -
          pdflatex paml.tex
      - name: Set up temporary directory for testing artifacts
        run: |
          echo "GH_TMPDIR=$(mktemp -d)" >> $GITHUB_ENV  # Export the shell temp dir out to the Github CI runner
          echo ${{ env.GH_TMPDIR }}
      - name: "Upload spec document"
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: specification-document
          path: ./paml.pdf
          retention-days: 1
